### ISSUE TITLE
Mapping tree back to transmission events

### ISSUE THREAD

**Issue by stevenweaver** [wdelva/SimpactCyanExamples#2]
Dear all, 

An event in the transmission log looks like so:

`49.0332732934,transmission,woman_5008,5008,1,21.8952359931,man_4902,4902,0,24.9396708742,originSPVL,140098.4374561198`

However, IDs in the the ` C.Epidemic_seed.seq.bis.sim.nwk.fasta` file look like so:
`11.1.C`

How would one map that ID back to the actual transmission event?

Best,
Steven

**Comment by niyukuri** [comment]
Hi,

To map the ID back to the actual transmission event use the transmission network built by transmission.network.builder() function, which is a list of transmission subnetworks produced by all seed individuals (when we seed HIV infection, we choose randomly N individuals, and each will have a transmission network). For each sub-network, you have a transmission table, and original IDs are named **RecId**. IDs you see on the tree have three parts: **X.Y.C**, where **X** is the number of the sub-network (_Xth_ seed), **Y**is the new label of original label **RecId** following the transmission order (seed has 0, 1st infection has 1, 2nd infection has 2, etc), and **C** is the type of HIV strain. The 11.1.C ID meant that the sequence was sampled from 11th transmission sub-network (11th seed).

Best,

**Comment by stevenweaver** [comment]
Dear @niyukuri, 

I was able to understand. Thank you. I'll write a conversion function shortly. 

Best,
Steven
